### ISSUE TITLE
Show number of projects in admin view of user

### ISSUE THREAD

**Issue by brianharvey** [snap-cloud/SnapSite#75]
I just banned a user (livecoder) for spamming.  It would be nice if I could easily have found out if they'd actually made any projects, apart from spamming the forum; if so, I might have put more effort into the decision.

Also, shouldn't the admin dashboard have a button to administer projects, besides users?  That would help clueless admins such as me try to recover users' projects.

**Comment by bromagosa** [comment]
You can see public projects for any user. Are you asking for admins to be able to see people's private projects? This could be a politically hairy one :)

(I know there are many admin features missing, we ran out of funding when I was in the middle of implementing them. Some day I'll get back to it...)

**Comment by brianharvey** [comment]
I'm just asking for the _number_ of projects, without switching to a different screen.
