### ISSUE TITLE
Can't flag project

### ISSUE THREAD

**Issue by brianharvey** [snap-cloud/SnapSite#80]
I tried to flag a project and got this:
<img width="1551" alt="Firefox001" src="https://user-images.githubusercontent.com/3885074/76322792-0ddc0080-62a1-11ea-8cab-049472d897a0.png">

I had just flagged another project by this user, if that's relevant.

**Comment by bromagosa** [comment]
Hmm, sounds like the project was already flagged. The flagging system is very raw and needs a lot of work.

I'll look into it someday when I have some time for the cloud & site again...

**Comment by Daniel4-Scratch** [comment]
Wow, some people are weird on snap... Also an idea for the snap<i>!</i> team, maye add an option where on a mod account you can delete projects straight away.

**Comment by brianharvey** [comment]
> straight away

Are you coming to Snap!Con?  I want to hear your accent!  (I once spent a few hours on Oxford Street in London just listening to people talk.)

**Comment by Daniel4-Scratch** [comment]
I'm Australian, not so much of an accent to me.

**Comment by brianharvey** [comment]
No accent?  I can barely understand Australians when they're speaking to each other.  (They slow down for me.)  But we should stop hijacking the repo.

**Comment by bromagosa** [comment]
This is fixed now. We've got a revamped flagging system :)
