### ISSUE TITLE
Website overflows when there is a big username

### ISSUE THREAD

**Issue by R4356th** [snap-cloud/SnapSite#90]
Here is a screenshot (for Firefox)-
![Screenshot (74)](https://user-images.githubusercontent.com/61620631/87585138-6b290800-c700-11ea-8ca1-bee7ec58dd69.png)
The same should also happen for big project names.

**Comment by R4356th** [comment]
This happens everywhere.

**Comment by Daniel4-Scratch** [comment]
Why would someone even have a long username?

**Comment by R4356th** [comment]
Well, you can just add seven (or was that six?) more characters to your own username, you will view an overflow yourself.
